spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/psm?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver